service: tidy-contactform

useDotenv: true

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs16.x
  deploymentMethod: direct
  httpApi:
    cors:
      allowedOrigins:
        - http://localhost:5173
      allowedHeaders:
        - Content-Type
      allowedMethods:
        - POST

functions:
  tidy-contactform:
    handler: index.handler
    name: tidy-contactform
    events:
      - httpApi:
          method: POST
          path: /

plugins:
  - serverless-plugin-typescript
  - serverless-offline
